#ifndef __XSEED_CONSTANTS_H__
#define __XSEED_CONSTANTS_H__
enum error_codes_e
{
    XSEED_SEEK_ERROR = -1,
    XSEED_BAD_INPUT = -2,
    XSEED_MALLOC_ERROR = -3
};


enum data_encodings_e
{
    XSEED_TEXT = 0,
    XSEED_UINT16 = 1,
    XSEED_UINT32 = 3,
    XSEED_FLOAT = 4,
    XSEED_DOUBLE = 5,
    XSEED_STEIM1 = 10,
    XSEED_STEIM2 = 11,
    XSEED_STEIM3 = 19,
    XSEED_COMPRESS_INT16 = 50,
    XSEED_COMPRESS_INT32 = 51,
    XSEED_COMPRESS_FLOAT = 52,
    XSEED_COMPRESS_DOUBLE = 53,
    XSEED_OPAQUE = 100
};

#endif /* __XSEED_CONSTANTS_H__ */
