#ifndef __XSEED_CONSTANTS_H__
#define __XSEED_CONSTANTS_H__
enum error_codes_e
{
    XSEED_SUCCESS,
    XSEED_BAD_INPUT,
    XSEED_MALLOC_ERROR,
    XSEED_INVALID_DATATYPE,
    XSEED_NULL_PASSED
};

enum data_encodings_e
{
    XSEED_TEXT = 0,
    XSEED_UINT16 = 1,
    XSEED_UINT32 = 3,
    XSEED_FLOAT = 4,
    XSEED_DOUBLE = 5,
    XSEED_STEIM1 = 10,
    XSEED_STEIM2 = 11,
    XSEED_STEIM3 = 19,
    XSEED_COMPRESS_INT32 = 53,
    XSEED_COMPRESS_FLOAT = 54,
    XSEED_COMPRESS_DOUBLE = 55,
    XSEED_OPAQUE = 100
};

#endif /* __XSEED_CONSTANTS_H__ */
